"""Crypto asset aliases shared by price parsing and price lookup."""

from __future__ import annotations

# User alias -> Binance spot symbol (USDT pair)
ASSET_ALIASES: dict[str, str] = {
    "btc": "BTCUSDT",
    "bitcoin": "BTCUSDT",
    "биткоин": "BTCUSDT",
    "биткоина": "BTCUSDT",
    "битка": "BTCUSDT",
    "биток": "BTCUSDT",
    "eth": "ETHUSDT",
    "ethereum": "ETHUSDT",
    "эфир": "ETHUSDT",
    "эфира": "ETHUSDT",
    "эфиру": "ETHUSDT",
    "sol": "SOLUSDT",
    "solana": "SOLUSDT",
    "солана": "SOLUSDT",
    "соланы": "SOLUSDT",
    "bnb": "BNBUSDT",
    "xrp": "XRPUSDT",
    "ripple": "XRPUSDT",
    "doge": "DOGEUSDT",
    "dogecoin": "DOGEUSDT",
    "доги": "DOGEUSDT",
    "ton": "TONUSDT",
    "toncoin": "TONUSDT",
    "тон": "TONUSDT",
    "тона": "TONUSDT",
    "ada": "ADAUSDT",
    "cardano": "ADAUSDT",
    "trx": "TRXUSDT",
    "tron": "TRXUSDT",
    "ltc": "LTCUSDT",
    "litecoin": "LTCUSDT",
    "avax": "AVAXUSDT",
    "link": "LINKUSDT",
    "chainlink": "LINKUSDT",
    "dot": "DOTUSDT",
    "polkadot": "DOTUSDT",
    "matic": "MATICUSDT",
    "polygon": "MATICUSDT",
}
